### ISSUE TITLE
Race condition messing up regex matches

### ISSUE THREAD

**Issue by pj-hugo** [cultab/themr#5]
I'm using Starship as my shell prompt and in my config file I have two lines defining specific colors for directories and git information. I'm running themr v0.2.4

This is how that part of my starship.toml looks like:
```
[palettes.custom]
dir = '#8BA4B0'
git = '#8A9A7B'
```
And this is my themr config.yaml that targets those two lines:
```
starship_dir:
    path: "~/.config/starship/starship.toml"
    regex: "dir = '#.*'"
    replace: "dir = '{}'"

starship_git:
    path: "~/.config/starship/starship.toml"
    regex: "git = '.*'"
    replace: "git = '{}'"
```
And then I have colors defined in my themes.yaml:
```
kanagawa-wave:
  nvim: "kanagawa-wave"
  wezterm: 'Kanagawa (Gogh)'
  starship_dir: '#7E9CD8'
  starship_git: '#76946A'

kanagawa-dragon:
  nvim: "kanagawa-dragon"
  wezterm: 'Kanagawa Dragon (Gogh)'
  starship_dir: '#8BA4B0'
  starship_git: '#8A9A7B'
```

The issue is that I'm getting some sort of race condition when switching between my themes that causes the regex match to fail. This is the error message I get when that happens:
```
❯ themr kanagawa-wave
ERRO Configuration: Regex `dir = '#.*'` failed to match in file: ~/.config/starship/starship.toml
```
But if I run `themr -d` for debugging mode it works without any issues, no race condition or error messages but then I get the debug info which I'm not necessarily interested in all the time. Is there some way that I can get the changes to run consecutively but without the debug information printed?
